### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by Khashkhuu** [edriang/react-connect-context-hooks#12]
Would you like to update the library?

I want to React 16 -> 18
some warnings and not working (

warning " > react-connect-context-hooks@1.10.1" has unmet peer dependency "@types/react@^16.8".
warning " > react-connect-context-hooks@1.10.1" has incorrect peer dependency "react@^16.8.0".
warning " > react-connect-context-hooks@1.10.1" has incorrect peer dependency "react-dom@^16.8.0".
warning "react-connect-context-hooks > use-context-selection@1.4.3" has incorrect peer dependency "react@^16.0.0 || ^17.0.0".

**Comment by edriang** [comment]
Hello there! thanks for your interest in the library.. I've been quickly exploring and it seems that updating to v18 will require library updates, because of the new "by default" concurrent rendering (see https://github.com/reactwg/react-18/discussions/70)

I'll try to dig into this issue in the following weeks, but I cannot commit to a deadline.

**Comment by Khashkhuu** [comment]
thanks for response.

**Comment by edriang** [comment]
@Khashkhuu can you please help me testing a beta version of the library?

You can try `npm install react-connect-context-hooks@2.0.0-beta`

I replaced `use-context-selection` with `use-context-selector`, which does not depend on `unstable_changedBytes` property from `createContext` (which was removed on React 18)

If this works fine for you I'll publish without the beta tag. Thanks in advance for your help

**Comment by Khashkhuu** [comment]
@edriang 

Works Fine now, I apperciate it :)
